version: '3.4'

services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db-server
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5000:5000
      - 5001:5001
  db-server:
    image: postgres
    restart: always
    container_name: db-server
    environment:
      - POSTGRES_PASSWORD=password123
    ports:
      - 1400:1433